<?php
include_once 'connectdb.php';
session_start();

// If BACKUP is requested, stream SQL and exit before rendering HTML
if (isset($_POST['action']) && $_POST['action'] === 'backup') {
  try {
    $pdo->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);

    
    $dbStmt = $pdo->query('SELECT DATABASE() as db');
    $dbRow = $dbStmt->fetch(PDO::FETCH_ASSOC);
    $databaseName = $dbRow && isset($dbRow['db']) ? $dbRow['db'] : 'database';

    $tables = [];
    $q = $pdo->query('SHOW TABLES');
    while ($r = $q->fetch(PDO::FETCH_NUM)) {
      $tables[] = $r[0];
    }

    $dump  = "-- Backup generated by Utilities on " . date('Y-m-d H:i:s') . "\n";
    $dump .= "-- Database: `{$databaseName}`\n\n";
    $dump .= "SET FOREIGN_KEY_CHECKS=0;\n\n";

    foreach ($tables as $table) {
      // Drop + Create
      $createStmt = $pdo->query("SHOW CREATE TABLE `{$table}`");
      $createRow = $createStmt->fetch(PDO::FETCH_ASSOC);
      $createSql = $createRow && isset($createRow['Create Table']) ? $createRow['Create Table'] : '';
      $dump .= "--\n-- Structure for table `{$table}`\n--\n\n";
      $dump .= "DROP TABLE IF EXISTS `{$table}`;\n";
      $dump .= $createSql . ";\n\n";

      // Data
      $dataStmt = $pdo->query("SELECT * FROM `{$table}`");
      $rows = $dataStmt->fetchAll(PDO::FETCH_ASSOC);
      if ($rows) {
        $dump .= "--\n-- Data for table `{$table}`\n--\n";
        foreach ($rows as $row) {
          $cols = array_map(function($c){ return "`" . str_replace("`", "``", $c) . "`"; }, array_keys($row));
          $vals = array_map(function($v) use ($pdo){
            if ($v === null) return 'NULL';
            return $pdo->quote($v);
          }, array_values($row));
          $dump .= "INSERT INTO `{$table}` (" . implode(",", $cols) . ") VALUES (" . implode(",", $vals) . ");\n";
        }
        $dump .= "\n";
      }
    }

    $dump .= "SET FOREIGN_KEY_CHECKS=1;\n";

    $filename = 'backup_' . $databaseName . '_' . date('Ymd_His') . '.sql';
    header('Content-Type: application/sql');
    header('Content-Disposition: attachment; filename=' . $filename);
    header('Content-Length: ' . strlen($dump));
    echo $dump;
    exit;
  } catch (Throwable $e) {
    $_SESSION['status'] = 'Backup failed: ' . $e->getMessage();
    $_SESSION['status_code'] = 'error';
    header('Location: utilities.php');
    exit;
  }
}

// Handle RESTORE (SQL file upload)
if (isset($_POST['action']) && $_POST['action'] === 'restore') {
  try {
    if (!isset($_FILES['sqlfile']) || !is_uploaded_file($_FILES['sqlfile']['tmp_name'])) {
      throw new RuntimeException('No SQL file uploaded');
    }
    $sql = file_get_contents($_FILES['sqlfile']['tmp_name']);
    if ($sql === false) {
      throw new RuntimeException('Cannot read uploaded SQL file');
    }

    $pdo->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
    $pdo->beginTransaction();

    // Split statements on semicolon followed by newline; keep it simple
    $statements = preg_split('/;\s*\n/', $sql);
    foreach ($statements as $statement) {
      $trim = trim($statement);
      if ($trim === '' || stripos($trim, '--') === 0 || stripos($trim, '/*') === 0) {
        continue;
      }
      $pdo->exec($trim);
    }

    $pdo->commit();
    $_SESSION['status'] = 'Database restored successfully';
    $_SESSION['status_code'] = 'success';
  } catch (Throwable $e) {
    if ($pdo->inTransaction()) {
      $pdo->rollBack();
    }
    $_SESSION['status'] = 'Restore failed: ' . $e->getMessage();
    $_SESSION['status_code'] = 'error';
  }
  header('Location: utilities.php');
  exit;
}

// Handle ADD STOCK by Product Code (column `product` in tbl_product)
if (isset($_POST['action']) && $_POST['action'] === 'add_stock') {
  try {
    $productCode = isset($_POST['product_code']) ? trim($_POST['product_code']) : '';
    $quantity = isset($_POST['quantity']) ? (int)$_POST['quantity'] : 0;
    if ($productCode === '' || $quantity <= 0) {
      throw new InvalidArgumentException('Provide a valid product code and positive quantity');
    }

    $pdo->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);

    // Ensure row exists
    $chk = $pdo->prepare('SELECT stock FROM tbl_product WHERE product = :p LIMIT 1');
    $chk->execute([':p' => $productCode]);
    $row = $chk->fetch(PDO::FETCH_ASSOC);
    if (!$row) {
      throw new RuntimeException('Product not found: ' . htmlspecialchars($productCode));
    }

    $upd = $pdo->prepare('UPDATE tbl_product SET stock = COALESCE(stock,0) + :q WHERE product = :p');
    $upd->execute([':q' => $quantity, ':p' => $productCode]);

    $_SESSION['status'] = 'Stock updated successfully';
    $_SESSION['status_code'] = 'success';
  } catch (Throwable $e) {
    $_SESSION['status'] = 'Add stock failed: ' . $e->getMessage();
    $_SESSION['status_code'] = 'error';
  }
  header('Location: utilities.php');
  exit;
}

include_once 'header.php';

// Fetch products for monitoring
$products = [];
try {
  $stmt = $pdo->query('SELECT product, category, brand, COALESCE(stock,0) as stock FROM tbl_product ORDER BY stock ASC, product ASC');
  $products = $stmt->fetchAll(PDO::FETCH_ASSOC);
} catch (Throwable $e) {
  $products = [];
}

// Low stock threshold (default 5)
$lowThreshold = isset($_GET['low']) ? max(0, (int)$_GET['low']) : 5;
?>

  <div class="content-wrapper">
    <div class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1 class="m-0">Utilities</h1>
          </div>
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right"></ol>
          </div>
        </div>
      </div>
    </div>

    <div class="content">
      <div class="container-fluid">
        <div class="row">
          <div class="col-lg-12">

            <div class="accordion" id="utilitiesAccordion">

              <!-- Backup & Restore -->
              <div class="card">
                <div class="card-header p-0" id="headingBackup">
                  <h2 class="mb-0">
                    <button class="btn btn-link btn-block text-left p-3" type="button" data-toggle="collapse" data-target="#collapseBackup" aria-expanded="true" aria-controls="collapseBackup">
                      Backup &amp; Restore
                    </button>
                  </h2>
                </div>
                <div id="collapseBackup" class="collapse show" aria-labelledby="headingBackup" data-parent="#utilitiesAccordion">
                  <div class="card-body">
                    <div class="row">
                      <div class="col-md-6">
                        <form method="post">
                          <input type="hidden" name="action" value="backup">
                          <button type="submit" class="btn btn-success">Download Backup (SQL)</button>
                        </form>
                      </div>
                      <div class="col-md-6">
                        <form method="post" enctype="multipart/form-data">
                          <input type="hidden" name="action" value="restore">
                          <div class="form-group">
                            <label>Restore from SQL file:</label>
                            <input type="file" name="sqlfile" accept=".sql,text/sql" class="form-control-file" required>
                          </div>
                          <button type="submit" class="btn btn-warning" onclick="return confirm('This will modify the database. Proceed?')">Restore</button>
                        </form>
                      </div>
                    </div>
                  </div>
                </div>
              </div>

              <!-- Add Stock -->
              <div class="card">
                <div class="card-header p-0" id="headingAddStock">
                  <h2 class="mb-0">
                    <button class="btn btn-link btn-block text-left p-3 collapsed" type="button" data-toggle="collapse" data-target="#collapseAddStock" aria-expanded="false" aria-controls="collapseAddStock">
                      Add Stock
                    </button>
                  </h2>
                </div>
                <div id="collapseAddStock" class="collapse" aria-labelledby="headingAddStock" data-parent="#utilitiesAccordion">
                  <div class="card-body">
                    <form method="post">
                      <input type="hidden" name="action" value="add_stock">
                      <div class="form-row">
                        <div class="form-group col-md-6">
                          <label>Product Code</label>
                          <input type="text" class="form-control" name="product_code" placeholder="Enter Product Code (tbl_product.product)" required>
                        </div>
                        <div class="form-group col-md-3">
                          <label>Quantity to Add</label>
                          <input type="number" class="form-control" name="quantity" min="1" step="1" required>
                        </div>
                      </div>
                      <button type="submit" class="btn btn-primary">Add Stock</button>
                    </form>
                  </div>
                </div>
              </div>

              <!-- Stock Monitoring -->
              <div class="card">
                <div class="card-header p-0" id="headingStockMonitor">
                  <h2 class="mb-0">
                    <button class="btn btn-link btn-block text-left p-3 collapsed" type="button" data-toggle="collapse" data-target="#collapseStockMonitor" aria-expanded="false" aria-controls="collapseStockMonitor">
                      Stock Monitoring
                    </button>
                  </h2>
                </div>
                <div id="collapseStockMonitor" class="collapse" aria-labelledby="headingStockMonitor" data-parent="#utilitiesAccordion">
                  <div class="card-body">
                    <form method="get" class="form-inline mb-3">
                      <label class="mr-2">Low stock threshold</label>
                      <input type="number" class="form-control mr-2" name="low" value="<?php echo (int)$lowThreshold; ?>" min="0" step="1">
                      <button class="btn btn-secondary" type="submit">Apply</button>
                    </form>

                    <div class="table-responsive">
                      <table class="table table-hover table-striped">
                        <thead>
                          <tr>
                            <th>Product Code</th>
                            <th>Category</th>
                            <th>Brand</th>
                            <th class="text-right">Stock</th>
                            <th>Status</th>
                          </tr>
                        </thead>
                        <tbody>
                        <?php if (!$products): ?>
                          <tr><td colspan="5" class="text-center">No data</td></tr>
                        <?php else: ?>
                          <?php foreach ($products as $p): ?>
                            <?php
                              $stock = (int)$p['stock'];
                              $low = $stock <= $lowThreshold;
                            ?>
                            <tr <?php echo $low ? 'style="background-color:#fff3cd"' : ''; ?>>
                              <td><?php echo htmlspecialchars($p['product']); ?></td>
                              <td><?php echo htmlspecialchars($p['category']); ?></td>
                              <td><?php echo htmlspecialchars((string)$p['brand']); ?></td>
                              <td class="text-right"><?php echo number_format($stock); ?></td>
                              <td>
                                <?php if ($low): ?>
                                  <span class="badge badge-warning">Low</span>
                                <?php else: ?>
                                  <span class="badge badge-success">OK</span>
                                <?php endif; ?>
                              </td>
                            </tr>
                          <?php endforeach; ?>
                        <?php endif; ?>
                        </tbody>
                      </table>
                    </div>
                  </div>
                </div>
              </div>

              <!-- Activity Log -->
              <div class="card">
                <div class="card-header p-0" id="headingActivity">
                  <h2 class="mb-0">
                    <button class="btn btn-link btn-block text-left p-3 collapsed" type="button" data-toggle="collapse" data-target="#collapseActivity" aria-expanded="false" aria-controls="collapseActivity">
                      Activity Log
                    </button>
                  </h2>
                </div>
                <div id="collapseActivity" class="collapse" aria-labelledby="headingActivity" data-parent="#utilitiesAccordion">
                  <div class="card-body">
                    <p>Open the Activity Log to review recorded actions.</p>
                    <a href="activity_log.php" class="btn btn-info">Open Activity Log</a>
                  </div>
                </div>
              </div>

              <!-- Archive  (Admin Only) -->
              <?php if(isset($_SESSION['role']) && $_SESSION['role'] === 'Admin'): ?>
              <div class="card">
                <div class="card-header p-0" id="headingArchive">
                  <h2 class="mb-0">
                    <button class="btn btn-link btn-block text-left p-3 collapsed" type="button" data-toggle="collapse" data-target="#collapseArchive" aria-expanded="false" aria-controls="collapseArchive">
                      <i class="fas fa-archive"></i> Archive
                    </button>
                  </h2>
                </div>
                <div id="collapseArchive" class="collapse" aria-labelledby="headingArchive" data-parent="#utilitiesAccordion">
                  <div class="card-body">
                    <p>Manage archived transactions. View, restore, or permanently delete archived orders.</p>
                    <?php
                    // Check if archive tables exist
                    try {
                      $checkTable = $pdo->query("SHOW TABLES LIKE 'tbl_invoice_archive'");
                      if ($checkTable->rowCount() === 0) {
                        // Tables don't exist, show setup button
                        echo '<a href="archive_setup.php" class="btn btn-warning">';
                        echo '<i class="fas fa-database"></i> Setup Archive Tables';
                        echo '</a>';
                      } else {
                        // Tables exist, show normal button
                        echo '<a href="archive.php" class="btn btn-warning">';
                        echo '<i class="fas fa-archive"></i> Open Archive';
                        echo '</a>';
                      }
                    } catch (Exception $e) {
                      // If error, show setup button
                      echo '<a href="archive_setup.php" class="btn btn-warning">';
                      echo '<i class="fas fa-database"></i> Setup Archive Tables';
                      echo '</a>';
                    }
                    ?>
                  </div>
                </div>
              </div>
              <?php endif; ?>

              <!-- Change Password -->
              <div class="card">
                <div class="card-header p-0" id="headingChangePass">
                  <h2 class="mb-0">
                    <button class="btn btn-link btn-block text-left p-3 collapsed" type="button" data-toggle="collapse" data-target="#collapseChangePass" aria-expanded="false" aria-controls="collapseChangePass">
                      Change Password
                    </button>
                  </h2>
                </div>
                <div id="collapseChangePass" class="collapse" aria-labelledby="headingChangePass" data-parent="#utilitiesAccordion">
                  <div class="card-body">
                    <p>Change your account password.</p>
                    <a href="changepassword.php" class="btn btn-warning">Change Password</a>
                  </div>
                </div>
              </div>

            </div>

          </div>
        </div>
      </div>
    </div>
  </div>

<?php include_once 'footer.php'; ?>

<?php if(isset($_SESSION['status']) && $_SESSION['status']!==''): ?>
<script>
Swal && Swal.fire({
  icon: '<?php echo $_SESSION['status_code'];?>',
  title: '<?php echo $_SESSION['status'];?>'
});
</script>
<?php unset($_SESSION['status']); endif; ?>